package io.aegiscloud.controlplane.store;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.aegiscloud.controlplane.cache.CacheService;
import io.aegiscloud.controlplane.domain.Models;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * AegisCloud's data access layer, backed by PostgreSQL.
 *
 * <p>Queries are written out as SQL against the schema in {@code db/migration}
 * rather than generated by an ORM: the aggregate reads here — the fleet rollup, the
 * SLO join against each objective's latest budget snapshot — are the shape the
 * dashboard needs, and expressing them directly keeps the round-trip count visible.
 */
@Repository
public class PlatformStore {

    private static final Logger log = LoggerFactory.getLogger(PlatformStore.class);
    private static final String OVERVIEW_CACHE_KEY = "aegiscloud:overview:v1";
    private static final Duration OVERVIEW_TTL = Duration.ofSeconds(30);

    private final JdbcTemplate jdbc;
    private final CacheService cache;
    private final ObjectMapper mapper;

    public PlatformStore(JdbcTemplate jdbc, CacheService cache, ObjectMapper mapper) {
        this.jdbc = jdbc;
        this.cache = cache;
        this.mapper = mapper;
    }

    /* ------------------------------- registry ------------------------------- */

    public List<Models.Cluster> clusters() {
        return jdbc.query("""
                SELECT id::text, name, provider_type, COALESCE(distribution,''), COALESCE(region,''),
                       status, node_count, COALESCE(k8s_version,''), is_local
                FROM cluster WHERE is_active ORDER BY is_local DESC, name
                """, CLUSTER_MAPPER);
    }

    private static final RowMapper<Models.Cluster> CLUSTER_MAPPER = (rs, n) -> new Models.Cluster(
            rs.getString(1),
            rs.getString(2),
            Models.ProviderType.valueOf(rs.getString(3)),
            rs.getString(4),
            rs.getString(5),
            Models.ClusterStatus.valueOf(rs.getString(6)),
            rs.getInt(7),
            rs.getString(8),
            rs.getBoolean(9));

    public List<Models.Service> services() {
        return jdbc.query("""
                SELECT id::text, name, COALESCE(owner_team,''), COALESCE(description,''), tags::text
                FROM service ORDER BY name
                """, (rs, n) -> new Models.Service(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                readStringMap(rs.getString(5))));
    }

    public List<Models.DeploymentTarget> targets() {
        return jdbc.query("""
                SELECT t.id::text, t.service_id::text, sv.name, t.cluster_id::text, c.name, c.provider_type,
                       COALESCE(c.region,''), t.namespace, t.scaling_strategy, t.deployment_status,
                       t.replicas, t.desired_replicas, t.reliability_score, t.availability_pct,
                       t.latency_p95_ms, t.error_rate_pct, t.monthly_cost_usd
                FROM deployment_target t
                JOIN service sv ON sv.id = t.service_id
                JOIN cluster c  ON c.id  = t.cluster_id
                WHERE t.is_active
                ORDER BY sv.name, c.name
                """, (rs, n) -> new Models.DeploymentTarget(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                Models.ProviderType.valueOf(rs.getString(6)),
                rs.getString(7),
                rs.getString(8),
                Models.ScalingStrategy.valueOf(rs.getString(9)),
                Models.DeploymentStatus.valueOf(rs.getString(10)),
                rs.getInt(11),
                rs.getInt(12),
                rs.getDouble(13),
                rs.getDouble(14),
                rs.getDouble(15),
                rs.getDouble(16),
                rs.getDouble(17)));
    }

    /* ------------------------------ objectives ------------------------------ */

    /**
     * Joins each SLO to its most recent error-budget snapshot with a LATERAL
     * subquery, so objective and current burn state arrive in one round trip
     * instead of one query per SLO.
     */
    public List<Models.Slo> slos() {
        return jdbc.query("""
                SELECT s.id::text, s.target_id::text, sv.name || ' @ ' || c.name, s.sli_type,
                       s.objective_value, s.window_days, COALESCE(b.current_value,0),
                       COALESCE(b.budget_remaining_pct,100), COALESCE(b.burn_rate,0)
                FROM slo s
                JOIN deployment_target t ON t.id = s.target_id
                JOIN service sv ON sv.id = t.service_id
                JOIN cluster c  ON c.id  = t.cluster_id
                LEFT JOIN LATERAL (
                    SELECT current_value, budget_remaining_pct, burn_rate
                    FROM error_budget_snapshot
                    WHERE slo_id = s.id ORDER BY computed_at DESC LIMIT 1
                ) b ON true
                WHERE s.is_active
                ORDER BY b.burn_rate DESC NULLS LAST
                """, (rs, n) -> new Models.Slo(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                Models.SliType.valueOf(rs.getString(4)),
                rs.getDouble(5),
                rs.getInt(6),
                rs.getDouble(7),
                rs.getDouble(8),
                rs.getDouble(9)));
    }

    /* ---------------------------- control plane ----------------------------- */

    public List<Models.ScalingEvent> scalingEvents() {
        return scalingEvents(50);
    }

    public List<Models.ScalingEvent> scalingEvents(int limit) {
        return jdbc.query("""
                SELECT e.id::text, e.target_id::text, sv.name || ' @ ' || c.name, e.previous_replicas,
                       e.new_replicas, e.trigger_metric, e.trigger_value, e.strategy, e.decided_at
                FROM scaling_event e
                JOIN deployment_target t ON t.id = e.target_id
                JOIN service sv ON sv.id = t.service_id
                JOIN cluster c  ON c.id  = t.cluster_id
                ORDER BY e.decided_at DESC LIMIT ?
                """, (rs, n) -> new Models.ScalingEvent(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getInt(4),
                rs.getInt(5),
                rs.getString(6),
                rs.getDouble(7),
                Models.ScalingStrategy.valueOf(rs.getString(8)),
                instant(rs, 9)), limit);
    }

    public List<Models.HealingEvent> healingEvents() {
        return healingEvents(50);
    }

    public List<Models.HealingEvent> healingEvents(int limit) {
        return jdbc.query("""
                SELECT h.id::text, h.target_id::text, sv.name || ' @ ' || c.name, h.pod_name, h.reason,
                       h.action_taken, h.detected_at, h.resolved_at
                FROM healing_event h
                JOIN deployment_target t ON t.id = h.target_id
                JOIN service sv ON sv.id = t.service_id
                JOIN cluster c  ON c.id  = t.cluster_id
                ORDER BY h.detected_at DESC LIMIT ?
                """, (rs, n) -> new Models.HealingEvent(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                instant(rs, 7),
                instant(rs, 8)), limit);
    }

    public List<Models.Policy> policies() {
        return jdbc.query("""
                SELECT p.id::text, p.cluster_id::text, c.name, p.max_replicas,
                       p.max_concurrent_experiments, p.protected_namespaces::text
                FROM policy p JOIN cluster c ON c.id = p.cluster_id
                ORDER BY c.name
                """, (rs, n) -> new Models.Policy(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getInt(4),
                rs.getInt(5),
                readStringList(rs.getString(6))));
    }

    /* -------------------------------- alerts -------------------------------- */

    public List<Models.Alert> alerts() {
        return jdbc.query("""
                SELECT a.id::text, a.target_id::text, sv.name || ' @ ' || c.name, a.severity, a.status,
                       a.message, a.opened_at
                FROM alert a
                JOIN deployment_target t ON t.id = a.target_id
                JOIN service sv ON sv.id = t.service_id
                JOIN cluster c  ON c.id  = t.cluster_id
                ORDER BY a.opened_at DESC
                """, (rs, n) -> new Models.Alert(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                Models.AlertSeverity.valueOf(rs.getString(4)),
                Models.AlertStatus.valueOf(rs.getString(5)),
                rs.getString(6),
                instant(rs, 7)));
    }

    /**
     * Transitions an alert, returning false when no such alert exists. The cached
     * overview is dropped on success because the open-alert count it reports has
     * just changed.
     *
     * <p>The id is cast in SQL rather than parsed in Java so that a malformed id
     * cannot raise before the query runs — a bad id must read as "not found", not
     * as a server error.
     */
    public boolean setAlertStatus(String alertId, Models.AlertStatus status) {
        int updated = jdbc.update("""
                UPDATE alert SET status = ?,
                       acknowledged_at = CASE WHEN ? = 'ACKNOWLEDGED' THEN now() ELSE acknowledged_at END,
                       resolved_at     = CASE WHEN ? = 'RESOLVED'     THEN now() ELSE resolved_at END
                WHERE id::text = ?
                """, status.name(), status.name(), status.name(), alertId);

        if (updated == 0) {
            return false;
        }
        cache.invalidate(OVERVIEW_CACHE_KEY);
        return true;
    }

    /* ------------------------------ experiments ----------------------------- */

    public List<Models.ExperimentRun> experiments() {
        return jdbc.query("""
                SELECT r.id::text, sv.name, COALESCE(c.name,''), r.run_type,
                       COALESCE(r.fault_spec->>'type',''), r.status,
                       COALESCE(r.score_before,0), COALESCE(r.score_during,0), COALESCE(r.score_after,0),
                       r.started_at, r.ended_at
                FROM evaluation_run r
                JOIN service sv ON sv.id = r.service_id
                LEFT JOIN deployment_target t ON t.id = r.target_id
                LEFT JOIN cluster c ON c.id = t.cluster_id
                ORDER BY r.started_at DESC LIMIT 50
                """, (rs, n) -> new Models.ExperimentRun(
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                Models.RunType.valueOf(rs.getString(4)),
                rs.getString(5),
                Models.RunStatus.valueOf(rs.getString(6)),
                rs.getDouble(7),
                rs.getDouble(8),
                rs.getDouble(9),
                instant(rs, 10),
                instant(rs, 11)));
    }

    /* ------------------------------- overview ------------------------------- */

    /**
     * The dashboard rollup: the most expensive read in the API, so it is cached in
     * Redis for a short window and invalidated on mutation.
     */
    public Models.Overview overview() {
        Models.Overview cached = cache.get(OVERVIEW_CACHE_KEY, Models.Overview.class);
        if (cached != null) {
            return cached.withCacheHit(true);
        }

        Models.Overview fresh = computeOverview();
        cache.set(OVERVIEW_CACHE_KEY, fresh, OVERVIEW_TTL);
        return fresh;
    }

    private Models.Overview computeOverview() {
        Totals totals = jdbc.queryForObject("""
                SELECT (SELECT count(*) FROM cluster WHERE is_active),
                       (SELECT count(*) FROM cluster WHERE is_active AND status = 'HEALTHY'),
                       (SELECT count(*) FROM service),
                       (SELECT count(*) FROM deployment_target WHERE is_active),
                       (SELECT COALESCE(sum(replicas),0) FROM deployment_target WHERE is_active),
                       (SELECT count(*) FROM alert WHERE status = 'OPEN'),
                       (SELECT COALESCE(round(avg(reliability_score)::numeric,1),0) FROM deployment_target WHERE is_active),
                       (SELECT COALESCE(sum(monthly_cost_usd),0) FROM deployment_target WHERE is_active)
                """, (rs, n) -> new Totals(
                rs.getInt(1), rs.getInt(2), rs.getInt(3), rs.getInt(4),
                rs.getInt(5), rs.getInt(6), rs.getDouble(7), rs.getDouble(8)));

        List<Models.ProviderScore> byProvider = jdbc.query("""
                SELECT c.provider_type, round(avg(t.reliability_score)::numeric,1), count(*),
                       COALESCE(sum(t.monthly_cost_usd),0)
                FROM deployment_target t JOIN cluster c ON c.id = t.cluster_id
                WHERE t.is_active
                GROUP BY c.provider_type ORDER BY 2 DESC
                """, (rs, n) -> new Models.ProviderScore(
                Models.ProviderType.valueOf(rs.getString(1)),
                rs.getDouble(2),
                rs.getInt(3),
                rs.getDouble(4)));

        List<Models.ScalingEvent> recentScaling = scalingEvents(4);
        List<Models.HealingEvent> recentHealing = healingEvents(3);

        return new Models.Overview(
                totals.clusters(), totals.healthyClusters(), totals.services(), totals.targets(),
                totals.replicas(), totals.openAlerts(), totals.avgScore(), totals.monthlyCost(),
                byProvider,
                scoreTrend(),
                recentScaling,
                recentHealing,
                engineStatus(),
                observabilitySources(),
                false);
    }

    /**
     * The 14-day reliability trend, read from {@code reliability_score_snapshot}.
     *
     * <p>Nothing writes that table until the Evaluation Engine lands, so this
     * legitimately returns an empty series today. It is left empty rather than
     * filled with a generated curve: a chart drawn from invented numbers is
     * indistinguishable from a real one, which is exactly the confusion a
     * reliability platform cannot afford.
     */
    private List<Models.ScorePoint> scoreTrend() {
        return jdbc.query("""
                SELECT to_char(day, 'Mon DD'), round(score::numeric, 1)
                FROM (
                    SELECT date_trunc('day', window_end) AS day, avg(score) AS score
                    FROM reliability_score_snapshot
                    WHERE window_end >= now() - INTERVAL '14 days'
                    GROUP BY 1
                ) daily
                ORDER BY day
                """, (rs, n) -> new Models.ScorePoint(rs.getString(1), rs.getDouble(2)));
    }

    /**
     * Engine status derived from what the platform has actually recorded.
     *
     * <p>Each engine reports the count of actions it genuinely took in the last 24
     * hours, and engines that are not built yet say so. The alternative — a fixed
     * list claiming every engine is ACTIVE — would make the operator console lie
     * about the platform's own health, which is a strange property for the thing
     * whose job is telling you when something is wrong.
     */
    private List<Models.EngineStatus> engineStatus() {
        int scaling = count("SELECT count(*) FROM scaling_event WHERE decided_at > now() - INTERVAL '24 hours'");
        int healing = count("SELECT count(*) FROM healing_event WHERE detected_at > now() - INTERVAL '24 hours'");
        int experiments = count("SELECT count(*) FROM evaluation_run WHERE started_at > now() - INTERVAL '24 hours'");
        int samples = count("SELECT count(*) FROM metric_sample WHERE sampled_at > now() - INTERVAL '24 hours'");
        int policies = count("SELECT count(*) FROM policy");

        return List.of(
                // Cluster rows carry a status column, but nothing has yet contacted a
                // Kubernetes API to populate it. Reporting that stored value as live
                // reachability would be a claim this engine cannot support, so it
                // reports its real state until the connectivity probe exists.
                new Models.EngineStatus("Deployment Engine", "NOT_IMPLEMENTED",
                        "Cluster connectivity is not yet probed", 0),
                new Models.EngineStatus("Auto-Scaling",
                        scaling > 0 ? "ACTIVE" : "IDLE", "Scaling decisions recorded", scaling),
                new Models.EngineStatus("Self-Healing",
                        healing > 0 ? "ACTIVE" : "IDLE", "Pod recovery actions recorded", healing),
                new Models.EngineStatus("Policy Engine",
                        policies > 0 ? "ENFORCING" : "UNCONFIGURED",
                        policies + " cluster guardrail(s) configured", policies),
                new Models.EngineStatus("Evaluation Engine",
                        samples > 0 ? "ACTIVE" : "NOT_IMPLEMENTED",
                        "Telemetry ingestion arrives in Phase 5", samples),
                new Models.EngineStatus("Experiment Engine",
                        experiments > 0 ? "ACTIVE" : "IDLE", "Chaos runs recorded", experiments));
    }

    /**
     * Observability backends, reported by what is actually configured.
     *
     * <p>Prometheus, Loki and Tempo are part of the target architecture but nothing
     * connects to them until the Evaluation Engine phase. They are listed as
     * NOT_CONFIGURED so the console shows the real integration state and lights up
     * on its own once those connections exist.
     */
    private List<Models.ObservabilitySource> observabilitySources() {
        boolean hasSamples = count("SELECT count(*) FROM metric_sample") > 0;
        String status = hasSamples ? "CONNECTED" : "NOT_CONFIGURED";
        String rate = hasSamples ? samplesPerSecond() : "—";

        return List.of(
                new Models.ObservabilitySource("Prometheus", "Metrics", status, rate),
                new Models.ObservabilitySource("Loki", "Logs", "NOT_CONFIGURED", "—"),
                new Models.ObservabilitySource("Tempo", "Traces", "NOT_CONFIGURED", "—"));
    }

    private String samplesPerSecond() {
        Double perSecond = jdbc.queryForObject("""
                SELECT count(*)::float / 3600
                FROM metric_sample WHERE sampled_at > now() - INTERVAL '1 hour'
                """, Double.class);
        return String.format("%.1f samples/s", perSecond == null ? 0 : perSecond);
    }

    private int count(String sql) {
        Integer value = jdbc.queryForObject(sql, Integer.class);
        return value == null ? 0 : value;
    }

    private record Totals(int clusters, int healthyClusters, int services, int targets,
                          int replicas, int openAlerts, double avgScore, double monthlyCost) {
    }

    /* -------------------------------- helpers ------------------------------- */

    /** Reads a nullable TIMESTAMPTZ column as an Instant. */
    private static Instant instant(ResultSet rs, int column) throws SQLException {
        Timestamp ts = rs.getTimestamp(column);
        return ts == null ? null : ts.toInstant();
    }

    private Map<String, String> readStringMap(String json) {
        if (json == null || json.isBlank()) {
            return Map.of();
        }
        try {
            return mapper.readValue(json, new TypeReference<Map<String, String>>() {
            });
        } catch (Exception e) {
            log.warn("could not parse JSONB object, treating as empty: {}", e.getMessage());
            return Map.of();
        }
    }

    private List<String> readStringList(String json) {
        if (json == null || json.isBlank()) {
            return List.of();
        }
        try {
            return mapper.readValue(json, new TypeReference<List<String>>() {
            });
        } catch (Exception e) {
            log.warn("could not parse JSONB array, treating as empty: {}", e.getMessage());
            return List.of();
        }
    }
}
